"""
AI Farm Advisor Service for AgriLens AI.
Primary: Google Gemini API.
Fallback: Rule-based recommendation engine.
"""
import os
import logging
import httpx
import json

logger = logging.getLogger(__name__)

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
GEMINI_URL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent"


async def generate_recommendations(
    farm_name: str,
    crop: str,
    weather: dict,
    soil: dict,
    satellite: dict,
    risks: dict,
    yield_data: dict,
) -> list[dict]:
    """
    Generate actionable farm recommendations.
    Uses Gemini if key is available, otherwise rule-based engine.
    """
    if GEMINI_API_KEY:
        try:
            recs = await _gemini_recommendations(
                farm_name, crop, weather, soil, satellite, risks, yield_data
            )
            logger.info("Recommendations generated by Gemini AI")
            return recs
        except Exception as e:
            logger.warning(f"Gemini failed ({e}), using rule-based fallback")

    return _rule_based_recommendations(crop, weather, soil, satellite, risks, yield_data)


async def _gemini_recommendations(
    farm_name, crop, weather, soil, satellite, risks, yield_data
) -> list[dict]:
    """Call Gemini API to generate structured recommendations."""
    prompt = f"""
You are an expert agricultural advisor. Based on the following farm data for "{farm_name}", 
generate exactly 4 concise, actionable farming recommendations.

Farm Data:
- Primary Crop: {crop}
- Weather: Temperature {weather.get('temperature_c')}°C, Humidity {weather.get('humidity')}%, 
  Current Rainfall {weather.get('rainfall_mm')} mm, 7-day Forecast Rain {weather.get('forecast_rain_mm')} mm
- Soil: pH {soil.get('ph')}, Nitrogen {soil.get('nitrogen')}, Phosphorus {soil.get('phosphorus')}, 
  Potassium {soil.get('potassium')}, Moisture {soil.get('moisture')}%
- NDVI (Vegetation Health): {satellite.get('ndvi_current')} — {satellite.get('vegetation_status')}
- Predicted Yield: {yield_data.get('predicted_tons_per_hectare')} t/ha
- Risk Levels: Drought {risks.get('drought', {}).get('score')}%, 
  Flood {risks.get('flood', {}).get('score')}%, 
  Crop Stress {risks.get('crop_stress', {}).get('score')}%

Respond ONLY with a JSON array of exactly 4 objects. Each object must have:
- "priority": "High", "Medium", or "Low"
- "text": concise recommendation (1-2 sentences, specific to the data above)
- "icon": a single relevant emoji

Example format:
[{{"priority": "High", "text": "Your recommendation here.", "icon": "💧"}}]

Do not include any markdown, explanation, or text outside the JSON array.
"""

    payload = {
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": {"temperature": 0.4, "maxOutputTokens": 800},
    }

    async with httpx.AsyncClient(timeout=20.0) as client:
        resp = await client.post(
            GEMINI_URL,
            params={"key": GEMINI_API_KEY},
            json=payload,
        )
        resp.raise_for_status()
        data = resp.json()

    text = data["candidates"][0]["content"]["parts"][0]["text"]
    # Strip markdown code fences if present
    text = text.strip().removeprefix("```json").removesuffix("```").strip()
    recommendations = json.loads(text)
    return recommendations[:4]


def _rule_based_recommendations(
    crop, weather, soil, satellite, risks, yield_data
) -> list[dict]:
    """
    Generate prioritised recommendations from rule-based logic.
    Used when Gemini API key is not available.
    """
    recs = []
    temperature = weather.get("temperature_c", 28)
    humidity = weather.get("humidity", 65)
    rainfall = weather.get("rainfall_mm", 10)
    forecast_rain = weather.get("forecast_rain_mm", 20)
    moisture = soil.get("moisture", 50)
    nitrogen = soil.get("nitrogen", "Medium")
    ph = soil.get("ph", 6.5)
    ndvi = satellite.get("ndvi_current", 0.55)
    drought_score = risks.get("drought", {}).get("score", 30)
    flood_score = risks.get("flood", {}).get("score", 20)
    stress_score = risks.get("crop_stress", {}).get("score", 30)

    # Irrigation recommendation
    if forecast_rain > 30 and moisture > 50:
        recs.append({
            "priority": "High",
            "text": f"Heavy rain ({forecast_rain} mm) is forecast and soil moisture is already at {moisture}%. Postpone irrigation and ensure drainage channels are clear.",
            "icon": "💧",
        })
    elif moisture < 35 or drought_score > 60:
        recs.append({
            "priority": "High",
            "text": f"Drought risk is elevated ({drought_score}%) and soil moisture is low ({moisture}%). Initiate irrigation immediately, preferably in early morning.",
            "icon": "🚿",
        })
    else:
        recs.append({
            "priority": "Low",
            "text": f"Soil moisture ({moisture}%) is within a healthy range. Monitor before the next irrigation cycle — expected rainfall of {forecast_rain} mm may reduce need.",
            "icon": "💧",
        })

    # Nutrient recommendation
    if nitrogen == "Low":
        recs.append({
            "priority": "High",
            "text": f"Nitrogen levels are Low — apply a nitrogen-rich fertilizer (Urea or DAP) before the next growth stage to improve yield for {crop}.",
            "icon": "🌱",
        })
    elif nitrogen == "Medium":
        recs.append({
            "priority": "Medium",
            "text": f"Nitrogen is at Medium levels. Consider a light top-dressing of nitrogen fertilizer at the next growth stage to maximise {crop} yield.",
            "icon": "🌿",
        })
    else:
        recs.append({
            "priority": "Low",
            "text": f"Nitrogen levels are High — no additional nitrogen fertilization needed. Excess nitrogen can increase disease risk for {crop}.",
            "icon": "✅",
        })

    # pH recommendation
    if ph < 5.5:
        recs.append({
            "priority": "Medium",
            "text": f"Soil pH ({ph}) is too acidic for {crop}. Apply agricultural lime to raise pH towards 6.0-6.5 before the next season.",
            "icon": "⚗️",
        })
    elif ph > 8.0:
        recs.append({
            "priority": "Medium",
            "text": f"Soil pH ({ph}) is alkaline. Consider applying sulphur or gypsum to lower pH and improve nutrient availability for {crop}.",
            "icon": "⚗️",
        })
    else:
        recs.append({
            "priority": "Low",
            "text": f"Soil pH ({ph}) is within the optimal range for {crop}. No lime or pH amendment is required this season.",
            "icon": "✅",
        })

    # NDVI / vegetation monitoring
    if ndvi < 0.4:
        recs.append({
            "priority": "High",
            "text": f"Vegetation health (NDVI: {ndvi}) is below healthy levels. Inspect the farm for pest damage, waterlogging, or nutrient deficiency.",
            "icon": "🛰️",
        })
    elif ndvi < 0.6:
        recs.append({
            "priority": "Medium",
            "text": f"Vegetation health (NDVI: {ndvi}) is moderate. Continue monitoring weekly — if NDVI drops further, check for disease or nutrient stress.",
            "icon": "🛰️",
        })
    else:
        recs.append({
            "priority": "Low",
            "text": f"Vegetation health looks good (NDVI: {ndvi}). Maintain current management practices and schedule routine field inspections.",
            "icon": "🌾",
        })

    # Keep highest priority first, limit to 4
    priority_order = {"High": 0, "Medium": 1, "Low": 2}
    recs.sort(key=lambda r: priority_order.get(r["priority"], 3))
    return recs[:4]
